packages:
  - frontend
  - docs

overrides:
  devalue@5.7.1: 5.8.1
  devalue@5.8.0: 5.8.1
  brace-expansion@5.0.5: 5.0.6
  ws@8.18.3: 8.20.1
  ws@8.20.0: 8.20.1

allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  core-js: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

minimumReleaseAgeExclude:
  - '@eslint/markdown@8.0.2'
  - stylelint@17.12.0
  - '@rolldown/binding-android-arm64@1.0.2'
  - '@rolldown/binding-darwin-arm64@1.0.2'
  - '@rolldown/binding-darwin-x64@1.0.2'
  - '@rolldown/binding-freebsd-x64@1.0.2'
  - '@rolldown/binding-linux-arm-gnueabihf@1.0.2'
  - '@rolldown/binding-linux-arm64-gnu@1.0.2'
  - '@rolldown/binding-linux-arm64-musl@1.0.2'
  - '@rolldown/binding-linux-ppc64-gnu@1.0.2'
  - '@rolldown/binding-linux-s390x-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-musl@1.0.2'
  - '@rolldown/binding-openharmony-arm64@1.0.2'
  - '@rolldown/binding-wasm32-wasi@1.0.2'
  - '@rolldown/binding-win32-arm64-msvc@1.0.2'
  - '@rolldown/binding-win32-x64-msvc@1.0.2'
  - rolldown@1.0.2
  - vite@8.0.14
